# Generated by Django 5.2.5 on 2025-08-13 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_user_date_joined"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="balance",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Accumulated NSSF/pension balance",
                max_digits=12,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="nssf_number",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
