# Generated by Django 5.2.5 on 2025-08-13 22:11

import django.db.models.deletion
import reports.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=180)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("account_summary", "Account Summary"),
                            ("payments", "Payments"),
                            ("requests", "Service Requests"),
                        ],
                        max_length=64,
                    ),
                ),
                (
                    "format",
                    models.CharField(
                        choices=[
                            ("csv", "CSV"),
                            ("xlsx", "Excel (XLSX)"),
                            ("json", "JSON"),
                            ("pdf", "PDF"),
                        ],
                        max_length=8,
                    ),
                ),
                ("params", models.JSONField(blank=True, default=dict)),
                (
                    "file",
                    models.FileField(
                        blank=True, null=True, upload_to=reports.models.report_upload_to
                    ),
                ),
                ("size_bytes", models.PositiveBigIntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("running", "Running"),
                            ("done", "Done"),
                            ("error", "Error"),
                        ],
                        default="queued",
                        max_length=24,
                    ),
                ),
                ("error_message", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("generated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "owner",
                    models.ForeignKey(
                        help_text="Who requested/owns this report",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
    ]
