# Generated by Django 5.2.5 on 2025-08-13 13:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["user", "was_read", "sent_at"],
                name="notificatio_user_id_a881ec_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["was_read", "sent_at"], name="notificatio_was_rea_f9ba74_idx"
            ),
        ),
    ]
