import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Box, Container, Typography, Card, CardContent, CardHeader, Grid, Accordion, AccordionSummary, AccordionDetails, TextField, Button, Stack, Link as MUILink, } from "@mui/material";
import ExpandMoreIcon from "@mui/icons-material/ExpandMore";
import SupportAgentIcon from "@mui/icons-material/SupportAgent";
import MarkEmailReadIcon from "@mui/icons-material/MarkEmailRead";
import ShieldOutlinedIcon from "@mui/icons-material/ShieldOutlined";
export default function Support() {
    return (_jsx(Box, { sx: { py: { xs: 4, md: 8 } }, children: _jsxs(Container, { maxWidth: "lg", children: [_jsxs(Stack, { spacing: 1, alignItems: "center", textAlign: "center", sx: { mb: 4 }, children: [_jsx(SupportAgentIcon, { color: "primary", sx: { fontSize: 36 } }), _jsx(Typography, { variant: "h4", fontWeight: 800, children: "Support" }), _jsx(Typography, { variant: "body1", color: "text.secondary", sx: { maxWidth: 720 }, children: "Find answers to common questions or reach out to our support team." })] }), _jsxs(Grid, { container: true, spacing: 3, children: [_jsx(Grid, { item: true, xs: 12, md: 7, children: _jsxs(Card, { variant: "outlined", children: [_jsx(CardHeader, { title: "Frequently Asked Questions" }), _jsxs(CardContent, { children: [_jsxs(FaqItem, { q: "How do I reset my password?", children: ["Go to the sign-in page and choose ", _jsx("strong", { children: "Forgot password" }), ". You\u2019ll receive an email with a secure link to reset it."] }), _jsxs(FaqItem, { q: "Where can I see my payment history?", children: ["Navigate to ", _jsx("strong", { children: "Payments" }), " to see status, history and download statements."] }), _jsxs(FaqItem, { q: "How do I update my beneficiaries?", children: ["Open ", _jsx("strong", { children: "Profile & Beneficiaries" }), ", edit the relevant section and save changes."] }), _jsx(FaqItem, { q: "Is my data secure?", children: "Yes. We use strong encryption, access controls, and privacy-by-design practices." })] })] }) }), _jsx(Grid, { item: true, xs: 12, md: 5, children: _jsxs(Card, { variant: "outlined", sx: { height: "100%" }, children: [_jsx(CardHeader, { title: "Contact us" }), _jsx(CardContent, { children: _jsxs(Stack, { spacing: 2, children: [_jsx(TextField, { label: "Your email", type: "email", fullWidth: true }), _jsx(TextField, { label: "Subject", fullWidth: true }), _jsx(TextField, { label: "Message", fullWidth: true, multiline: true, minRows: 4 }), _jsx(Button, { variant: "contained", startIcon: _jsx(MarkEmailReadIcon, {}), children: "Send message" }), _jsx(Typography, { variant: "caption", color: "text.secondary", children: "For sensitive account changes, we may verify your identity for your protection." })] }) })] }) })] }), _jsx(Card, { variant: "outlined", sx: { mt: 3 }, children: _jsx(CardContent, { children: _jsxs(Stack, { direction: { xs: "column", sm: "row" }, spacing: 2, alignItems: "center", children: [_jsx(ShieldOutlinedIcon, { color: "primary" }), _jsxs(Typography, { variant: "body2", color: "text.secondary", sx: { flex: 1 }, children: ["Beware of phishing. We will never ask for your password by email. Always check the website domain and contact us via the official channels listed here. Learn more at", " ", _jsx(MUILink, { href: "#", underline: "hover", children: "Security best practices" }), "."] })] }) }) })] }) }));
}
function FaqItem({ q, children }) {
    return (_jsxs(Accordion, { disableGutters: true, children: [_jsx(AccordionSummary, { expandIcon: _jsx(ExpandMoreIcon, {}), children: _jsx(Typography, { variant: "subtitle2", children: q }) }), _jsx(AccordionDetails, { children: _jsx(Typography, { variant: "body2", color: "text.secondary", children: children }) })] }));
}
