# Generated by Django 5.2.5 on 2025-08-13 11:30

import django.db.models.deletion
import profiles.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PensionerProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nssf_number", models.CharField(max_length=50, unique=True)),
                ("dob", models.DateField(blank=True, null=True)),
                ("national_id", models.CharField(blank=True, max_length=50)),
                ("address", models.CharField(blank=True, max_length=255)),
                ("city", models.CharField(blank=True, max_length=120)),
                ("bank_name", models.CharField(blank=True, max_length=120)),
                ("bank_account", models.CharField(blank=True, max_length=50)),
                ("next_of_kin_name", models.CharField(blank=True, max_length=120)),
                ("next_of_kin_phone", models.CharField(blank=True, max_length=30)),
                (
                    "avatar",
                    models.ImageField(
                        blank=True, null=True, upload_to=profiles.models.avatar_path
                    ),
                ),
                ("last_verified_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Beneficiary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=120)),
                ("relationship", models.CharField(max_length=60)),
                ("percentage", models.PositiveIntegerField()),
                ("phone", models.CharField(blank=True, max_length=30)),
                ("national_id", models.CharField(blank=True, max_length=50)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="beneficiaries",
                        to="profiles.pensionerprofile",
                    ),
                ),
            ],
        ),
    ]
